# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Solving Public Problems with Data | GovLab
email:
description: > # this means to ignore newlines until "baseurl:"
  Solving Public Problems with Data examines how data can be used to improve decision-making and problem solving in the public sector. The goal is to enable you to define and leverage the value of data to achieve your public mission.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

contentful:
    spaces:
      - site_data:
            space: ENV_CONTENTFUL_SPACE_ID
            access_token: ENV_CONTENTFUL_ACCESS_TOKEN

page_gen:
  - data: 'contentful.spaces.site_data.video'
    template: 'lecture'
    name: 'title'
    dir: 'lectures'
