# Ruby CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-ruby/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.4

    steps:
      - checkout

      - run: gem install bundler
      - run: bundle install
      - add_ssh_keys:
          fingerprints:
            - "78:57:ff:c9:2b:89:1b:ff:fe:d0:26:13:c7:c7:27:ba"
      - run: bash ./bin/automated.sh
